Parameters:
  IAMUserNames:
    Type: String
    Description: Comma-separated list of IAM user names to remove inactive access keys for.

Resources:
  RemoveInactiveKeysFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          IAM_USER_NAMES: !Ref IAMUserNames
          SNS_TOPIC_ARN: !Ref InactiveAccessKeyRemovalSNSTopic
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'iam:ListAccessKeys'
                - 'iam:DeleteAccessKey'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: !Ref InactiveAccessKeyRemovalSNSTopic

  DailyTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      ScheduleExpression: 'cron(0 12 * * ? *)'
      Targets:
        - Arn: !GetAtt RemoveInactiveKeysFunction.Arn
          Id: RemoveInactiveKeysFunctionTarget

  InactiveAccessKeyRemovalSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: IAM Access Key Removal Notifications

Outputs:
  RemoveInactiveKeysFunction:
    Description: Lambda function ARN
    Value: !GetAtt RemoveInactiveKeysFunction.Arn
  Role:
    Description: IAM role ARN
    Value: !GetAtt RemoveInactiveKeysFunctionRole.Arn
  SNSTopic:
    Description: SNS Topic ARN
    Value: !Ref InactiveAccessKeyRemovalSNSTopic