AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function to rotate IAM user access keys and notify via SNS,
  triggered by EventBridge.
Globals:
  Function:
    Timeout: 10
Parameters:
  IAMUserNames:
    Type: String
    Description: Comma-separated list of IAM user names to rotate access keys for.
Resources:
  RotateAccessKeysFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cf-templates-19qsu3g1qv8b5-ap-southeast-2/a6fc5bd690b3009367b7e2d39c47ac1e
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          IAM_USER_NAMES:
            Ref: IAMUserNames
          TopicArn:
            Ref: AccessKeyRotationSNSTopic
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - iam:ListAccessKeys
          - iam:DeleteAccessKey
          - sns:Publish
          Resource: '*'
        - Effect: Allow
          Action:
          - iam:CreateAccessKey
          Resource:
            Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:user/${IAMUserNames}
    Metadata:
      SamResourceId: RotateAccessKeysFunction
  NewAccessKeyTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
        - aws.iam
        detail-type:
        - AWS API Call via CloudTrail
        eventName:
        - CreateAccessKey
        requestParameters:
          userName:
          - Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:user/${IAMUserNames}
      Targets:
      - Arn:
          Fn::GetAtt:
          - RotateAccessKeysFunction
          - Arn
        Id: RotateAccessKeysFunctionTarget
    Metadata:
      SamResourceId: NewAccessKeyTrigger
  DailyTrigger:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      ScheduleExpression: cron(0 12 * * ? *)
      Targets:
      - Arn:
          Fn::GetAtt:
          - RotateAccessKeysFunction
          - Arn
        Id: RotateAccessKeysFunctionTarget
    Metadata:
      SamResourceId: DailyTrigger
  AccessKeyRotationSNSTopic:
    Type: AWS::SNS::Topic
    Metadata:
      SamResourceId: AccessKeyRotationSNSTopic
Outputs:
  RotateAccessKeysFunction:
    Description: Lambda function ARN
    Value:
      Fn::GetAtt:
      - RotateAccessKeysFunction
      - Arn
  Role:
    Description: IAM role ARN
    Value:
      Fn::GetAtt:
      - RotateAccessKeysFunctionRole
      - Arn
  SNSTopic:
    Description: SNS Topic ARN
    Value:
      Ref: AccessKeyRotationSNSTopic
