AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AccessKeyNotifierLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TOPIC_ARN: !Ref AccessKeyNotificationsTopic
      Policies:
        - AmazonSNSFullAccess
      Events:
        DailyEvent:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 day)'

  AccessKeyNotificationsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'Access Key Notifications'
      TopicName: 'access-key-notifications'

Outputs:
  AccessKeyNotifierLambdaArn:
    Description: 'ARN of the access key notifier lambda function'
    Value: !GetAtt AccessKeyNotifierLambda.Arn
  AccessKeyNotificationsTopicArn:
    Description: 'ARN of the access key notifications SNS topic'
    Value: !Ref AccessKeyNotificationsTopic
