AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  WebhookUrl:
    Type: String
    Description: URL of the Microsoft Teams webhook
    Default: your-webhook-url

Resources:
  CostAnomalyLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 30
      Events:
        Schedule:
          Type: 'Schedule'
          Properties:
            Schedule: 'rate(1 day)' # Adjust the schedule as desired
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookUrl
          THRESHOLD: '1000' # Adjust the cost anomaly threshold as desired
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-sam-role' # Replace with your actual role ARN
